# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  reactorGenerator:
    import: "package:reactor/generator.dart"
    builder_factories: ["reactorGenerator"]
    build_extensions: {".dart": ["reactor.g.dart"]}
    build_to: source
    auto_apply: dependents
    defaults:
      generate_for:
        # Only apply to .dart files in the web directory
        include:
        - web/**
        #- example/**
