# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config

targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        release_options:
          compiler: dart2js
          dart2js_args:
            # - -O3
            # - --csp
            - --no-minify
        enabled: true
