# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  reactorBuilder:
    import: "package:reactor/builder.dart"
    builder_factories: ["reactorBuilder"]
    build_extensions: {".dart": ["reactor.g.dart"]}
    build_to: source
    auto_apply: root_package
    defaults:
      generate_for:
        # Only apply to .dart files in the web directory
        include:
        - web/**
        #- example/**
