name: reactor

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  js: ^0.6.1
  source_gen: ^0.9.4+2
  meta: ^1.1.7
  pedantic: any

dev_dependencies:
  build_runner: ">=1.3.0 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"
  test: ^1.3.4
  build_test: any
  dart_style: '>=0.1.7 <2.0.0'
  dart_dev: ^2.0.0
