name: reactor
version: 0.1.2
homepage: https://github.com/KealJones/reactor
description: Reactor is a statically-typed Dart wrapper of ReactJS for building user interfaces.

environment:
  sdk: ^3.0.0

dependencies:
  js: ^0.6.7
  source_gen: ^1.3.2
  meta: ^1.9.1
  lints: ^2.1.0
  build: ^2.4.0

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.4
  build_web_compilers: ^4.0.3
  test: ^1.24.3
  build_test: ^2.1.7

