name: reactor
version: 0.2.0
homepage: https://github.com/KealJones/reactor
description: Reactor is a statically-typed Dart wrapper of ReactJS.

environment:
  sdk: ^3.0.2

dependencies:
  js: ^0.6.7

dev_dependencies:
  build_runner: ^2.4.4
  build_test: ^2.1.7
  build_web_compilers: ^4.0.3
  lints: ^2.1.0
  test: ^1.24.3
