name: reactor
version: 0.1.1
homepage: https://github.com/KealJones/reactor
description: Reactor is a statically-typed Dart wrapper of ReactJS for building user interfaces.

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  js: ^0.6.1
  source_gen: ^0.9.4+2
  meta: ^1.1.7
  pedantic: ^1.8.0+1
  dart_style: '>=0.1.7 <2.0.0'
  build: ^1.2.2
  analyzer: ^0.39.4

dev_dependencies:
  build_runner: ">=1.3.0 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"
  test: ^1.3.4
  build_test: any
  react_testing_library: ^0.1.0
  test_html_builder: ^1.0.0

